[package]
name = "ferrumc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.67"
tokio = "1.38.0"

ferrumc_utils = { path = "../ferrumc_utils"}
