[package]
name = "ferrumc-data-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
heck = "0.5"
tempfile = "3.10"
indicatif = "0.17"
zip = "0.6"
walkdir = "2"
